name: Audit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.7.0
      - name: Install bundler
        run: gem install bundler
      - name: Setup PG
        run: sudo apt-get -yqq install libpq-dev
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install Gems
        run: |
          bundle config path vendor/bundle
          bin/bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Security checks
        run: |
          bundle exec bundle-audit update
          bundle exec bundle-audit check
          bundle exec brakeman -A -w3
